version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    restart: always
    environment:
      - TZ=Asia/Seoul
      - DB_HOST=db
    volumes:
    - ./app/:/usr/asts/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10.2
    volumes:          #볼륨에 저장
      - postgres_data:/var/lib/postgres/data
    ports:
    - "5432:5432"
    healthcheck:                #상태 체크
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - POSTGRES_DB=asts
      - POSTGRES_PASSWORD=root
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asiz/Seoul
volumes:
  postgres_data:
