# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build and push docker image
        run: |
          set -x
          REPO="https://github.com/chb1828/portfolio.git"
          chmod +x gradlew
          ./gradlew clean build
          DOCKER_USER=sugarpowder
          DOCKER_PASS=sugar1234
          PRJ_NAME=asts
          PRJ_JAR=${PRJ_NAME}.jar
          docker build -t ${PRJ_NAME} --build-arg JAR_FILE=build/libs/${PRJ_JAR} ./
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker tag ${PRJ_NAME} ${DOCKER_USER}/${PRJ_NAME}:latest
          docker push ${DOCKER_USER}/${PRJ_NAME}
