# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ change-framework ]
  pull_request:
    branches: [ change-framework ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup VirtualEnv
        run: |
          pip install virtualenv
          python -m virtualenv venv
          . venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - name: Build and push Docker image
        env:
          TAG: ${0.1.{BUILD_NUMBER}}
          IMAGE_NAME: asts
          DOCKER_USER: sugarpowder
          DOCKER_PASS: sugar1234
        run: |
          echo $TAG
          echo $IMAGE_NAME
          echo $DOCKER_USER
          echo $DOCKER_PASS
          . venv/bin/activate
          docker build -t asts .
          docker login -u sugarpowder -p sugar1234
          docker tag asts sugarpowder/asts:latest
          docker push sugarpowder/asts
